CREATE TABLE IF NOT EXISTS discord_accounts (
  discord_id         BIGINT PRIMARY KEY,
  username           VARCHAR(255),
  global_name        VARCHAR(255),
  email              VARCHAR(320),
  avatar_hash        VARCHAR(255),
  commands_installed TINYINT(1) NOT NULL DEFAULT 0,
  updated_at         BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS oauth_tokens (
  discord_id   BIGINT PRIMARY KEY,
  access_enc   BLOB NOT NULL,
  refresh_enc  BLOB NOT NULL,
  token_type   VARCHAR(32) NOT NULL,
  scope        TEXT NOT NULL,
  expires_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL,
  CONSTRAINT fk_tokens_user FOREIGN KEY (discord_id)
    REFERENCES discord_accounts(discord_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mc_profiles (
  mc_uuid     VARCHAR(36) PRIMARY KEY,
  name        VARCHAR(64),
  last_ip     VARCHAR(45),
  platform    VARCHAR(16),
  updated_at  BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS links (
  discord_id  BIGINT NOT NULL,
  mc_uuid     VARCHAR(36) NOT NULL,
  active      TINYINT(1) NOT NULL DEFAULT 1,
  created_at  BIGINT NOT NULL,
  PRIMARY KEY (discord_id, mc_uuid),
  CONSTRAINT fk_links_user FOREIGN KEY (discord_id) REFERENCES discord_accounts(discord_id) ON DELETE CASCADE,
  CONSTRAINT fk_links_profile FOREIGN KEY (mc_uuid)  REFERENCES mc_profiles(mc_uuid)      ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_links_discord ON links(discord_id);
CREATE INDEX idx_links_mc      ON links(mc_uuid);

-- Add created_at to discord_accounts
SET @dbname = DATABASE();
SET @tablename = 'discord_accounts';
SET @columnname = 'created_at';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE (TABLE_SCHEMA = @dbname)
     AND (TABLE_NAME = @tablename)
     AND (COLUMN_NAME = @columnname)) > 0,
  'SELECT 1',
  'ALTER TABLE discord_accounts ADD COLUMN created_at BIGINT'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- Initialize created_at from updated_at
UPDATE discord_accounts SET created_at = updated_at WHERE created_at IS NULL;

-- Make created_at NOT NULL if it exists and isn't already
SET @preparedStatement = (SELECT IF(
  (SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_SCHEMA = @dbname AND TABLE_NAME = @tablename AND COLUMN_NAME = @columnname) = 'YES',
  'ALTER TABLE discord_accounts MODIFY COLUMN created_at BIGINT NOT NULL',
  'SELECT 1'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- Add profile_id to discord_accounts
SET @columnname = 'profile_id';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE (TABLE_SCHEMA = @dbname)
     AND (TABLE_NAME = @tablename)
     AND (COLUMN_NAME = @columnname)) > 0,
  'SELECT 1',
  'ALTER TABLE discord_accounts ADD COLUMN profile_id VARCHAR(255)'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- Note: profile_id will be generated by Java code (ProfileIdGenerator) using Base64 URL-safe encoding
-- Don't try to populate it here as SQL base64 encoding differs from Java's URL-safe Base64

CREATE UNIQUE INDEX IF NOT EXISTS idx_discord_profile_id ON discord_accounts(profile_id);

-- Add is_primary to links
SET @tablename = 'links';
SET @columnname = 'is_primary';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE (TABLE_SCHEMA = @dbname)
     AND (TABLE_NAME = @tablename)
     AND (COLUMN_NAME = @columnname)) > 0,
  'SELECT 1',
  'ALTER TABLE links ADD COLUMN is_primary TINYINT(1) NOT NULL DEFAULT 0'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;

-- Set first link as primary for each discord_id
UPDATE links l1
INNER JOIN (
    SELECT discord_id, mc_uuid
    FROM (
        SELECT discord_id, mc_uuid, created_at,
               ROW_NUMBER() OVER (PARTITION BY discord_id ORDER BY created_at ASC) as rn
        FROM links
        WHERE active = 1
    ) ranked
    WHERE rn = 1
) first_links ON l1.discord_id = first_links.discord_id AND l1.mc_uuid = first_links.mc_uuid
SET l1.is_primary = 1;

-- Add requires_reauth to discord_accounts
SET @tablename = 'discord_accounts';
SET @columnname = 'requires_reauth';
SET @preparedStatement = (SELECT IF(
  (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
   WHERE (TABLE_SCHEMA = @dbname)
     AND (TABLE_NAME = @tablename)
     AND (COLUMN_NAME = @columnname)) > 0,
  'SELECT 1',
  'ALTER TABLE discord_accounts ADD COLUMN requires_reauth TINYINT(1) NOT NULL DEFAULT 0'
));
PREPARE alterIfNotExists FROM @preparedStatement;
EXECUTE alterIfNotExists;
DEALLOCATE PREPARE alterIfNotExists;
