name: Bug report
description: Report a bug in LogDO2 (provide server, plugin version and logs)
title: "[Bug] "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks you for bug report — fill the fields below. **DO NOT SEND YOUR SECRETS FROM CONFIG (e.g discord.botToken, oauth.clientSecret or security.tokenEncryptionKeyBase64)**.
  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      description: Which LogDO2 version are you using?
      placeholder: e.g. 1.3
      required: true
  - type: input
    id: server_type
    attributes:
      label: Server core
      description: Paper/Folia
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal reproducible steps
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior (attach logs / stacktrace)
      description: Paste only relevant lines. Use a gist for long logs.
      required: true
  - type: input
    id: related_config
    attributes:
      label: Relevant config keys
      description: e.g. oauth.clientId, web.publicUrl (do NOT include secrets)
      required: false
  - type: dropdown
    id: impact
    attributes:
      label: Impact
      options:
        - Low
        - Medium
        - High
      required: true
