name: Feature request
description: Propose new functionality or enhancement
title: "[Feature] "
labels: ["enhancement"]
assignees: []
body:
  - type: input
    id: summary
    attributes:
      label: Short summary
      - type: textarea
    id: motivation
    attributes:
      label: Why is this useful?
  - type: textarea
    id: design
    attributes:
      label: Proposed design
      description: Describe how it should work; include examples
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
