CREATE TABLE IF NOT EXISTS discord_accounts (
  discord_id         BIGINT PRIMARY KEY,
  username           TEXT,
  global_name        TEXT,
  email              TEXT,
  avatar_hash        TEXT,
  commands_installed INTEGER NOT NULL DEFAULT 0,
  updated_at         BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_tokens (
  discord_id   BIGINT PRIMARY KEY,
  access_enc   BYTEA NOT NULL,
  refresh_enc  BYTEA NOT NULL,
  token_type   TEXT NOT NULL,
  scope        TEXT NOT NULL,
  expires_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL,
  CONSTRAINT fk_tokens_user FOREIGN KEY (discord_id)
    REFERENCES discord_accounts(discord_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mc_profiles (
  mc_uuid     TEXT PRIMARY KEY,
  name        TEXT,
  last_ip     TEXT,
  platform    TEXT,
  updated_at  BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
  discord_id  BIGINT NOT NULL,
  mc_uuid     TEXT   NOT NULL,
  active      INTEGER NOT NULL DEFAULT 1,
  created_at  BIGINT  NOT NULL,
  PRIMARY KEY (discord_id, mc_uuid),
  CONSTRAINT fk_links_user   FOREIGN KEY (discord_id) REFERENCES discord_accounts(discord_id) ON DELETE CASCADE,
  CONSTRAINT fk_links_profile FOREIGN KEY (mc_uuid)    REFERENCES mc_profiles(mc_uuid)      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_links_discord ON links(discord_id);
CREATE INDEX IF NOT EXISTS idx_links_mc      ON links(mc_uuid);

-- Add created_at to discord_accounts
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='discord_accounts' AND column_name='created_at'
    ) THEN
        ALTER TABLE discord_accounts ADD COLUMN created_at BIGINT;
        UPDATE discord_accounts SET created_at = updated_at WHERE created_at IS NULL;
        ALTER TABLE discord_accounts ALTER COLUMN created_at SET NOT NULL;
    END IF;
END $$;

-- Add profile_id to discord_accounts
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='discord_accounts' AND column_name='profile_id'
    ) THEN
        ALTER TABLE discord_accounts ADD COLUMN profile_id TEXT;
        -- Note: profile_id will be generated by Java code (ProfileIdGenerator) using Base64 URL-safe encoding
        -- Don't try to populate it here as SQL base64 encoding differs from Java's URL-safe Base64
        CREATE UNIQUE INDEX IF NOT EXISTS idx_discord_profile_id ON discord_accounts(profile_id);
    END IF;
END $$;

-- Add is_primary to links
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='links' AND column_name='is_primary'
    ) THEN
        ALTER TABLE links ADD COLUMN is_primary INTEGER NOT NULL DEFAULT 0;

        -- Set first link (by created_at) as primary for each discord_id
        WITH first_links AS (
            SELECT DISTINCT ON (discord_id) discord_id, mc_uuid
            FROM links
            WHERE active = 1
            ORDER BY discord_id, created_at ASC
        )
        UPDATE links
        SET is_primary = 1
        FROM first_links
        WHERE links.discord_id = first_links.discord_id
          AND links.mc_uuid = first_links.mc_uuid;
    END IF;
END $$;

-- Add requires_reauth to discord_accounts
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name='discord_accounts' AND column_name='requires_reauth'
    ) THEN
        ALTER TABLE discord_accounts ADD COLUMN requires_reauth INTEGER NOT NULL DEFAULT 0;
    END IF;
END $$;
