-- NOTE: This file is kept for documentation purposes only.
-- SQLite migrations are now handled programmatically in DatabaseManager.runSqliteMigrations()
-- to support conditional column additions (SQLite doesn't support ALTER TABLE IF NOT EXISTS).

PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS discord_accounts (
  discord_id         INTEGER PRIMARY KEY,
  username           TEXT,
  global_name        TEXT,
  email              TEXT,
  avatar_hash        TEXT,
  commands_installed INTEGER NOT NULL DEFAULT 0,
  updated_at         BIGINT NOT NULL,
  created_at         BIGINT,
  profile_id         TEXT
);

CREATE TABLE IF NOT EXISTS oauth_tokens (
  discord_id   INTEGER PRIMARY KEY,
  access_enc   BLOB NOT NULL,
  refresh_enc  BLOB NOT NULL,
  token_type   TEXT NOT NULL,
  scope        TEXT NOT NULL,
  expires_at   BIGINT NOT NULL,
  updated_at   BIGINT NOT NULL,
  FOREIGN KEY (discord_id) REFERENCES discord_accounts(discord_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mc_profiles (
  mc_uuid     TEXT PRIMARY KEY,
  name        TEXT,
  last_ip     TEXT,
  platform    TEXT,
  updated_at  BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
  discord_id  INTEGER NOT NULL,
  mc_uuid     TEXT    NOT NULL,
  active      INTEGER NOT NULL DEFAULT 1,
  created_at  BIGINT  NOT NULL,
  is_primary  INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (discord_id, mc_uuid),
  FOREIGN KEY (discord_id) REFERENCES discord_accounts(discord_id) ON DELETE CASCADE,
  FOREIGN KEY (mc_uuid)    REFERENCES mc_profiles(mc_uuid)      ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_links_discord ON links(discord_id);
CREATE INDEX IF NOT EXISTS idx_links_mc      ON links(mc_uuid);
CREATE UNIQUE INDEX IF NOT EXISTS idx_discord_profile_id ON discord_accounts(profile_id);

-- Initialize created_at from updated_at for rows that don't have it
UPDATE discord_accounts SET created_at = updated_at WHERE created_at IS NULL;

-- Note: profile_id will be generated by Java code (ProfileIdGenerator) using Base64 URL-safe encoding

-- Set first link as primary for each discord_id (idempotent)
WITH first_links AS (
    SELECT discord_id, mc_uuid, MIN(created_at) as min_created
    FROM links
    WHERE active = 1
    GROUP BY discord_id
)
UPDATE links
SET is_primary = 1
WHERE is_primary = 0 AND EXISTS (
    SELECT 1 FROM first_links
    WHERE links.discord_id = first_links.discord_id
      AND links.mc_uuid = first_links.mc_uuid
      AND links.created_at = first_links.min_created
);
